### ISSUE TITLE
Dunkle Schrift auf dunklem Grund

### ISSUE THREAD

**Issue by zirngipfel** [NickAtGit/pr0gramm-iOS#1]
Bei eingestelltem Light Mode in iOS ist die Schrift in der App dunkel auf dunklem Grund -> Die Schrift ist sehr schwer lesbar

Testgerät: 
iPhone 7, iOS 13.4.1

**Comment by NickAtGit** [comment]
Ist bekannt, muss ich noch angehen. App komplett wie die Website in Dark halten oder Light/Dark Mode anbieten?

**Comment by NickAtGit** [comment]
Ist in Build 5 behoben
