### ISSUE TITLE
App-Absturz beim Löschen von Suchverlauf

### ISSUE THREAD

**Issue by Anradh** [NickAtGit/pr0gramm-iOS#14]
Sucht man 2x nach dem selben Keyword, erscheint dieses 2x im Suchverlauf. Wird eines davon gelöscht, crasht die App. Evtl. wird hier nicht anhand des Eintrags, sondern (wohl fälschlicherweise) anhand des Texts gelöscht?

**Comment by NickAtGit** [comment]
Habe ich auch schon mal gehabt. Muss ich mir ansehen..

**Comment by NickAtGit** [comment]
Sollte behoben sein. Das eingeben eines identischen Suchbegriffes speichert diesen nicht erneut.
