### ISSUE TITLE
Post verlassen bei geöffneter Kommentar-Box

### ISSUE THREAD

**Issue by Anradh** [NickAtGit/pr0gramm-iOS#18]
Ein Post kann nicht verlassen werden, solange die Kommentar-Box geöffnet ist.

**Comment by Simorenarium** [comment]
Sollte der Kommentar gecached werden, falls man den post nochmal aufmacht oder einfach verwerfen?

**Comment by Anradh** [comment]
Meiner Ansicht nach solved. Konnte damals in der Kommentar-Ansicht nicht swipen / den Post schliessen. Funktioniert in der Zwischenzeit problemlos.
Ursprüngliche Issue hatte nichts mit Verfassen / Beantworten von Kommentaren zu tun. Sorry für die Unklarheit.
