### ISSUE TITLE
Animation beim Wischen zwischen Posts beschleunigen

### ISSUE THREAD

**Issue by saburch** [NickAtGit/pr0gramm-iOS#22]
Wird von einem Post zum Nächsten gewischt, dauert die Animation unnatürlich lange und es kommt vor, dass die View nicht "einrastet" und Posts übersprungen werden.

**Comment by NickAtGit** [comment]
Die Scrollgeschwindigkeit hängt vom Swipe deines Fingers ab. Wenn du schnell swipest gehts auch schneller. Hab da schon viel Zeit drin versenkt und bin eigentlich recht zufrieden damit. Nutze aber auch hauptsächlich das Links/Rechts tippen auf dem Bildrand um zum nächsten Hochlad zu kommen.

**Comment by saburch** [comment]
Okay, im Vergleich zur Android App finde ich es schrecklich.
Wenn ich schnell wische, dann passiert es des Öfteren, dass es einfach 2-3 Posts weiter scrollt.
Ich muss dazu sagen, dass ich die App auf dem iPad benutze. Teste das mal

**Comment by NickAtGit** [comment]
Für iPad ist noch nichts optimiert und das werde ich auch erst später machen. Habs schon auf nem iPad laufen lassen und habe das nicht so schlimm empfunden (aber ich weiß schon was du meinst). Warum nimmst du als workaround nicht das Links/Rechts tippen? (in den Settings anschalten)

**Comment by saburch** [comment]
Werde ich als Workaround machen, bin mir nur das Swipen von der Android App gewohnt ;-)
