### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Lefred1** [NickAtGit/pr0gramm-iOS#34]
Morje, funktioniert die app noch auf aktuellen ios Systemen? Und wenn ja, wie installiere ich die App? Sideloading kriege ich prinzipiell hin, aber ich habe keine Ahnung wie ich diese App auf mein iPhone kriege. Würde mich sehr über eine Antwort freuen, pr0gramm immer über safari oder andere browser zu nutzen fuckt schon ab.
Danke im Vorraus,
Grüße

**Comment by NickAtGit** [comment]
Moin: https://testflight.apple.com/join/NubTl9vH

**Comment by Lefred1** [comment]
Top, danke. Das war jetzt einfacher als erwartet.

**Comment by fabidoim** [comment]
Ist die App noch aktiv? Installation via TestFlight funktioniert leider nicht.
