### ISSUE TITLE
Posts laden nicht mehr

### ISSUE THREAD

**Issue by TimAufdemKampe** [NickAtGit/pr0gramm-iOS#46]
Moin, seit heute Morgen laden die Posts bei mir nicht mehr. Hat das Problem noch jemand?

Ich hab die App auch schon einmal neu installiert.

**Comment by iSack97** [comment]
Habe das selbe Problem, ein relogin bringt auch nichts…

**Comment by CharlyMurdoc** [comment]
Hallo, ist bei mir auch so. Neuinstallation der App oder Neustart von Handy hat auch nichts gebracht. Mein Account im Browser funktioniert, sollte also an der App liegen. Sonst keine Einstellungen am Handy geändert. Problem besteht seit gestern Nachmittag.

**Comment by ghost** [comment]
Gleiches Problem, Web ist okay, App nicht funktional.

**Comment by CharlyMurdoc** [comment]
Neue Version ist da. App geht wieder. Vielen Dank für den schnellen Fix
