### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Hotelecho** [NickAtGit/pr0gramm-iOS#49]
Moin, wie installiere ich Pr0 auf meinem iPhone? TestFlight sagt die Beta ist voll, gibt es noch eine andere Möglichkeit?

**Comment by b3n3w** [comment]
Moin, 

falls du einen Mac besitzt (Hackintosh geht auch), kannst du dir mit xCode die App selbst builden und installieren.

**Comment by NickAtGit** [comment]
Eigentlich sollte noch Platz sein. Ich habe ein paar Karteileichen entfernt. Probier noch mal.

**Comment by dnyyn** [comment]
Also bei mir spuckt es wieder aus, dass die Beta voll sei..

**Comment by NickAtGit** [comment]
@dnyyn ich hab wieder Platz geschafft.
