### ISSUE TITLE
Login schlägt fehl - Sonderzeichen oder Zeichenlänge im PW?

### ISSUE THREAD

**Issue by supaeasy** [NickAtGit/pr0gramm-iOS#6]
Sonderzeichen scheinen nicht zu funktionieren. Vielleicht ist es auch (zusätzlich) die Passwortlänge? Habe 20 Stellen mit Sonderzeichen getestet. Weder copyPaste noch manuelle Eingabe funktioniert.

**Comment by NickAtGit** [comment]
Done
